- name: Add a line to a file if the file does not exist, without passing regexp
  ansible.builtin.lineinfile:
    path: /etc/exports
    line: 20.126.59.242 kubemaster my-master-azure-vm
    create: yes
  become: true  

- name: Add a line to a file if the file does not exist, without passing regexp
  ansible.builtin.lineinfile:
    path: /etc/exports
    line: 20.126.129.132 kubenode1 my-worker1-azure-vm
    create: yes
  become: true      

- name: Add a line to a file if the file does not exist, without passing regexp
  ansible.builtin.lineinfile:
    path: /etc/exports
    line: 20.126.99.216 nfs my-NFS-azure-vm
    create: yes
  become: true     

