- name: Add a line to a file if the file does not exist, without passing regexp
  ansible.builtin.lineinfile:
    path: /etc/exports
    #line: 20.126.54.157 kubemaster my-master-azure-vm
    line: 10.0.1.10 kubemaster my-master-azure-vm
    create: yes
  become: true  

- name: Add a line to a file if the file does not exist, without passing regexp
  ansible.builtin.lineinfile:
    path: /etc/exports
    #line: 20.126.82.81 kubenode1 my-worker1-azure-vm
    line: 10.0.1.11 kubenode1 my-worker1-azure-vm
    create: yes
  become: true      

- name: Add a line to a file if the file does not exist, without passing regexp
  ansible.builtin.lineinfile:
    path: /etc/exports
    #line: 20.126.22.70 nfs my-NFS-azure-vm
    line: 10.0.1.13 nfs my-NFS-azure-vm
    create: yes
  become: true   




