- name: Add master to /etc/hosts
  ansible.builtin.lineinfile:
    path: /etc/hosts
    line: 10.0.1.10 kubemaster my-master-azure-vm
    create: yes
  become: true  

- name: Add worker to /etc/hosts
  ansible.builtin.lineinfile:
    path: /etc/hosts
    line: 10.0.1.11 kubenode1 my-worker1-azure-vm
    create: yes
  become: true      

- name: Add nfs to /etc/hosts
  ansible.builtin.lineinfile:
    path: /etc/hosts
    line: 10.0.1.13 nfs my-NFS-azure-vm
    create: yes
  become: true   




