- name: enable firewalld
  systemd:
    name: firewalld
    state: started
    enabled: True  
  become: true  

- name: comunicacion de PODS en el cluster mediante VXLAN paso 1
  command: "modprobe br_netfilter"
  become: true    

#transparent masquerading: para que los PODs puedan comunicarse dentro del cluster mediante VXLAN:
- name: comunicacion de PODS en el cluster mediante VXLAN paso 2
  command: "firewall-cmd --add-masquerade --permanent"
  become: true  

# SDN ports
- name: Add ports for SDN 1
  command: "firewall-cmd --permanent --add-port=8285/udp"
  become: true  

- name: Add ports for SDN 2
  command: "firewall-cmd --permanent --add-port=8472/udp"
  become: true    

# END SDN 

- name: firewall reload
  command: "firewall-cmd --reload"
  become: true       

   
