#opcion 1: https://phoenixnap.com/kb/ansible-create-file
# - name: K8s traffic with firewall
#     copy:
#       dest: "/etc/sysctl.d/k8s.conf"
#       content: |
#         net.bridge.bridge-nf-call-ip6tables = 1
#         net.bridge.bridge-nf-call-iptables  = 1
#         net.ipv4.ip_forward                 = 1
#   become: true      

#opcion 2
- name: Touch a file, using symbolic modes to set the permissions (equivalent to 0644)
  ansible.builtin.file:
    path: /etc/sysctl.d/k8s.conf
    state: touch
    mode: u=rw,g=r,o=r
  become: true          

- name: Add a line 
  ansible.builtin.lineinfile:
    path: /etc/sysctl.d/k8s.conf
    line: net.bridge.bridge-nf-call-ip6tables = 1
    create: yes
  become: true             

- name: Add a line 
  ansible.builtin.lineinfile:
    path: /etc/sysctl.d/k8s.conf
    line: net.bridge.bridge-nf-call-iptables = 1
    create: yes
  become: true        

- name: Add a line 
  ansible.builtin.lineinfile:
    path: /etc/sysctl.d/k8s.conf
    line: net.ipv4.ip_forward = 1
    create: yes 
  become: true          

- name: sysctl --system
  command: "sysctl --system"
  become: true    

- name: swapoff  -a
  command: "swapoff  -a"
  become: true  

- name: free -m
  command: "free -m"
  become: true      


- name: eliminar la línea del fichero /etc/fstab que monta en el arranque el swap
  ansible.builtin.lineinfile:
    path: /etc/fstab
    state: absent
    regexp: '^%swap'
  become: true  


