#opcion 1: https://phoenixnap.com/kb/ansible-create-file
# - name: K8s traffic with firewall
#     copy:
#       dest: "/etc/sysctl.d/k8s.conf"
#       content: |
#         net.bridge.bridge-nf-call-ip6tables = 1
#         net.bridge.bridge-nf-call-iptables  = 1
#         net.ipv4.ip_forward                 = 1
#   become: true      



# Para permitir que kubernetes maneje correctamente el tráfico con el cortafuegos:
#opcion 2
- name: creamos /etc/sysctl.d/k8s.conf
  ansible.builtin.file:
    path: /etc/sysctl.d/k8s.conf
    state: touch
    mode: u=rw,g=r,o=r
  become: true          

- name: Añadimos linea 1 a /etc/sysctl.d/k8s.conf
  ansible.builtin.lineinfile:
    path: /etc/sysctl.d/k8s.conf
    line: net.bridge.bridge-nf-call-ip6tables = 1
    create: yes
  become: true             

- name: Añadimos linea 2 a /etc/sysctl.d/k8s.conf
  ansible.builtin.lineinfile:
    path: /etc/sysctl.d/k8s.conf
    line: net.bridge.bridge-nf-call-iptables = 1
    create: yes
  become: true        

- name: Añadimos linea 3 a /etc/sysctl.d/k8s.conf
  ansible.builtin.lineinfile:
    path: /etc/sysctl.d/k8s.conf
    line: net.ipv4.ip_forward = 1
    create: yes 
  become: true          

- name: sysctl --system
  command: "sysctl --system"
  become: true  

#Swap es un espacio de intercambio que utiliza el disco duro, 
# en lugar de la RAM para almacenar datos temporalmente. Lo desactivamos
- name: swapoff  -a
  command: "swapoff  -a"
  become: true  

# este comando muestra info de la memoria. 
#- name: free -m
#  command: "free -m"
#  become: true      


- name: eliminar la línea del fichero /etc/fstab que monta en el arranque el swap
  ansible.builtin.lineinfile:
    path: /etc/fstab
    state: absent
    regexp: '^%swap'
  become: true  


