- name: Download stable.repo
  get_url:
    url: https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/CentOS_8_Stream/devel:kubic:libcontainers:stable.repo
    dest: /etc/yum.repos.d/devel:kubic:libcontainers:stable.repo
    mode: '0644'
  become: true  

- name: Download crio.repo
  get_url:
    url:  https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable:cri-o:1.23:1.23.1/CentOS_8_Stream/devel:kubic:libcontainers:stable:cri-o:1.23:1.23.1.repo
    dest: /etc/yum.repos.d/devel:kubic:libcontainers:stable:cri-o:1.23:1.23.1.repo
    mode: '0644'  
  become: true    

# - name: Configurar modulos del kernel necesarios para CRI-O
#     copy:
#       dest: "/etc/modules-load.d/crio.conf"
#       content: |
#         overlay
#         br_netfilter
#   become: true

- name: Touch a file, using symbolic modes to set the permissions (equivalent to 0644)
  ansible.builtin.file:
    path: /etc/modules-load.d/crio.conf
    state: touch
    mode: u=rw,g=r,o=r
  become: true          

- name: Add a line 
  ansible.builtin.lineinfile:
    path: /etc/modules-load.d/crio.conf
    line: overlay
    create: yes
  become: true       
       
- name: Add a line 
  ansible.builtin.lineinfile:
    path: /etc/modules-load.d/crio.conf
    line: br_netfilter
    create: yes
  become: true    

#  [root@host ~]# dnf install cri-o -y
#[root@host ~]# systemctl enable crio
#[root@host ~]# systemctl start crio

- name: instalar paquetes rpm 
  dnf: 
    name: 'cri-o'
    state: present
  become: true  


# - name: Make sure a firewall is running
#   systemd:
#     state: started
#     name: crio
#     enabled: yes
#   become: true 

- name: systemctl enable crio
  command: "systemctl enable crio"
  become: true  

- name: systemctl start crio
  command: "systemctl start crio"
  become: true    





       