- name: Download stable.repo
  get_url:
    url: https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/CentOS_8_Stream/devel:kubic:libcontainers:stable.repo
    dest: /etc/yum.repos.d/devel:kubic:libcontainers:stable.repo
    mode: '0644'
  become: true  

- name: Download crio.repo
  get_url:
    url:  https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable:cri-o:1.23:1.23.1/CentOS_8_Stream/devel:kubic:libcontainers:stable:cri-o:1.23:1.23.1.repo
    dest: /etc/yum.repos.d/devel:kubic:libcontainers:stable:cri-o:1.23:1.23.1.repo
    mode: '0644'  
  become: true    

# - name: Configurar modulos del kernel necesarios para CRI-O
#     copy:
#       dest: "/etc/modules-load.d/crio.conf"
#       content: |
#         overlay
#         br_netfilter
#   become: true


# Configurar modulos del kernel necesarios para CRI-O

- name: Touch a file, using symbolic modes to set the permissions (equivalent to 0644)
  ansible.builtin.file:
    path: /etc/modules-load.d/crio.conf
    state: touch
    mode: u=rw,g=r,o=r
  become: true          

- name: Add line 1 to /etc/modules-load.d/crio.conf
  ansible.builtin.lineinfile:
    path: /etc/modules-load.d/crio.conf
    line: overlay
    create: yes
  become: true       
       
- name: Add line 2 to /etc/modules-load.d/crio.conf 
  ansible.builtin.lineinfile:
    path: /etc/modules-load.d/crio.conf
    line: br_netfilter
    create: yes
  become: true    

  # instalamos el engine de contenedores

- name: instalar paquete cri-o 
  dnf: 
    name: 'cri-o'
    state: present
  become: true  


- name: Make sure crio is running
  systemd:
    name: crio
    state: started
    enabled: True
  become: true 




       