# - name: Configuramos el repositorio de kubernetes
#     copy:
#       dest: "/etc/yum.repos.d/kubernetes.repo"
#       content: |
#         [kubernetes]
#         name=Kubernetes
#         baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
#         enabled=1
#         gpgcheck=1
#         repo_gpgcheck=1
#         gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
#         exclude=kubelet kubeadm kubectl
#   become: true      

- name: Touch a file, using symbolic modes to set the permissions (equivalent to 0644)
  ansible.builtin.file:
    path: /etc/yum.repos.d/kubernetes.repo
    state: touch
    mode: u=rw,g=r,o=r
  become: true          

- name: Add a line 
  ansible.builtin.lineinfile:
    path: /etc/yum.repos.d/kubernetes.repo
    line: [kubernetes]
    create: yes
  become: true      

- name: Add a line 
  ansible.builtin.lineinfile:
    path: /etc/yum.repos.d/kubernetes.repo
    line: name=Kubernetes
    create: yes
  become: true      

- name: Add a line 
  ansible.builtin.lineinfile:
    path: /etc/yum.repos.d/kubernetes.repo
    line: baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
    create: yes
  become: true 

- name: Add a line 
  ansible.builtin.lineinfile:
    path: /etc/yum.repos.d/kubernetes.repo
    line: enabled=1
    create: yes
  become: true      

- name: Add a line 
  ansible.builtin.lineinfile:
    path: /etc/yum.repos.d/kubernetes.repo
    line: gpgcheck=1
    create: yes
  become: true      

- name: Add a line 
  ansible.builtin.lineinfile:
    path: /etc/yum.repos.d/kubernetes.repo
    line: repo_gpgcheck=1
    create: yes
  become: true      

- name: Add a line 
  ansible.builtin.lineinfile:
    path: /etc/yum.repos.d/kubernetes.repo
    line: gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
    create: yes
  become: true      

- name: Add a line 
  ansible.builtin.lineinfile:
    path: /etc/yum.repos.d/kubernetes.repo
    line: exclude=kubelet kubeadm kubectl
    create: yes
  become: true      


- name: install K8s 1
  command: "dnf install kubelet kubeadm kubectl -y --disableexcludes=Kubernetes"
  become: true 

- name: install K8s 2
  command: "systemctl enable kubelet"
  become: true 

- name: install K8s 3
  command: "systemctl start kubelet"
  become: true     


