- name: Añadimos el repo de kubernetes a /etc/yum.repos.d/
  copy:
    src: kubernetes.repo
    dest: /etc/yum.repos.d/kubernetes.repo
    owner: root
    group: root
    mode: "u=rw,g=r,o=r"
  become: true  

- name: install K8s 1
  command: "dnf install kubelet kubeadm kubectl --disableexcludes=kubernetes -y"
  become: true 

- name: enable kubelet
  systemd:
    name: kubelet
    state: started
    enabled: True 
  become: true    

# - name: install K8s 2
#   command: "systemctl enable kubelet"
#   become: true 

# - name: install K8s 3
#   command: "systemctl start kubelet"
#   become: true     


