- name: apply config step 1
  command: "exportfs -r"
  become: true  

- name: apply config step 2
  command: "exportfs -s"
  become: true    

# Didn't work: couldn't resolve module/action ansible.posix.firewalld

#- name: FirewallD rules
#  ansible.posix.firewalld:
#    permanent: yes
#    immediate: yes
#    service: "{{ item }}"
#    state: enabled
#  with_items:
#   - nfs
#   - rpc-bind
#   - mountd

#PGS: usar esto!!!! https://docs.ansible.com/ansible/2.5/modules/systemd_module.html
- name: enable firewalld
  command: "systemctl enable firewalld"
  become: true    

- name: start firewalld
  command: "systemctl start firewalld"
  become: true    

- name: add-service=nfs
  command: "firewall-cmd --permanent --add-service=nfs"
  become: true    

- name: add-service=rpc-bind
  command: "firewall-cmd --permanent --add-service=rpc-bind"
  become: true    

- name: add-service=mountd
  command: "firewall-cmd --permanent --add-service=mountd"
  become: true        

- name: firewall reload
  command: "firewall-cmd --reload"
  become: true    