- name: deploy ingress
  command: "kubectl apply -f https://raw.githubusercontent.com/haproxytech/kubernetes-ingress/master/deploy/haproxy-ingress.yaml"
  #become: true 



# Comprobaciones :
# kubectl get namespaces
# kubectl get pods --namespace=haproxy-controller



# Manual: del siguiente comando cogeremos el puerto para la security rule de Terraform.
# Es el que se encuentra mapeado al 80 de los contenedores
# [root@kubemaster ~]# kubectl get svc -A

