- name: export KUBECONFIG
  command: "export KUBECONFIG=/etc/kubernetes/admin.conf"
  become: true 

# Ojo: esto en la guia es con root pero se nos ha dicho que lo hagmos con adminUsername
- name: Create a directory /adminUsername/.kube if it does not exist
  ansible.builtin.file:
    path: /adminUsername/.kube
    state: directory
    mode: '0755'
  become: true   


# [root@kubemaster ~]# mkdir -p /root/.kube
# file

- name: kubernetes/admin.conf to root k8s root config
  command: "cp -i /etc/kubernetes/admin.conf /adminUsername/.kube/config"
  become: true 


# [root@kubemaster ~]# cp -i /etc/kubernetes/admin.conf /root/.kube/config
# command

- name: kubernetes/admin.conf to root k8s root config
  command: "chown $(id -u):$(id -g) /adminUsername/.kube/config"
  become: true 

# [root@kubemaster ~]# chown $(id -u):$(id -g) /root/.kube/config
# command


- name: export KUBECONFIG
  command: "kubectl get nodes"
  become: true 

