#- name: export KUBECONFIG
#  command: "export KUBECONFIG=/etc/kubernetes/admin.conf"
#  become: true 

# Ojo: esto en la guia es con root pero se nos ha dicho que lo hagmos con adminUsername
- name: Create a directory /home/adminUsername/.kube if it does not exist
  ansible.builtin.file:
    path: /home/adminUsername/.kube
    state: directory
    mode: '0755'
  become: true   


# [root@kubemaster ~]# mkdir -p /root/.kube
# file

##- name: kubernetes/admin.conf to root k8s root config
##  command: "cp -i /etc/kubernetes/admin.conf /home/adminUsername/.kube/config"
##  become: true 


# [root@kubemaster ~]# cp -i /etc/kubernetes/admin.conf /root/.kube/config
# command

- name: kubernetes/admin.conf to root k8s root config
  command: "chown adminUsername. /home/adminUsername/.kube/config"
  become: true 

# [root@kubemaster ~]# chown $(id -u):$(id -g) /root/.kube/config
# command

- name: Añadimos el repo de kubernetes a /etc/sudoers.d/
  copy:
    src: adminUsername
    dest: /etc/sudoers.d/adminUsername
    owner: root
    group: root
    mode: "u=rw,g=r,o=r"
  become: true  

#[root@kubemaster ~]# cat <<EOF > /etc/sudoers.d/adminUsername
#> ALL            ALL = (ALL) NOPASSWD: ALL
#> EOF


#Comprobar con:
#  command: "kubectl get nodes"

#[root@kubemaster ~]# mkdir -p /home/kubeadmin/.kube
#[root@kubemaster ~]# cp -i /etc/kubernetes/admin.conf /home/kubeadmin/.kube/config
#[root@kubemaster ~]# chown kubeadmin. /home/kubeadmin/.kube/config

 
