- name: open ports
  command: "firewall-cmd --zone=public --permanent --add-port={10250,30000-32767}/tcp"
  become: true   

- name: open ports
  command: "firewall-cmd --reload"
  become: true     

