- name: set-timezone
  command: "timedatectl set-timezone Europe/Madrid"
  become: true  

- name: instalar paquetes rpm 
  dnf: 
    name: 'chrony'
    state: present
  become: true  

#PGS: usar esto!!!! https://docs.ansible.com/ansible/2.5/modules/systemd_module.html

- name: enable chronyd
  systemd:
    name: chronyd
    state: started
    enabled: True 
  become: true   

# - name: enable chronyd
#   command: "systemctl enable chronyd"
#   become: true  

# - name: start chronyd
#   command: "systemctl start chronyd"
#   become: true    


- name: timedatectl set-ntp true
  command: "timedatectl set-ntp true"
  become: true  
