#Commented: didn't work: https://docs.ansible.com/ansible/latest/collections/ansible/posix/selinux_module.html
#- name: set-timezone
#  command: "ansible-galaxy collection install ansible.posix"
#  become: true  

#- name: Disable SELinux
#  ansible.posix.selinux:
#    state: disabled
#  become: true   

#This didn`t work either
#- name: Disabling SELinux state
#  selinux:
#    state: disabled
#  become: true    

- name: Disabling SELinux
  command: "sed -i s/=enforcing/=disabled/g /etc/selinux/config"
  become: true  