#Commented: didn't work: https://docs.ansible.com/ansible/latest/collections/ansible/posix/selinux_module.html

#- name: Disable SELinux
#  ansible.posix.selinux:
#    state: disabled
#  become: true   

#This didn`t work either
#- name: Disabling SELinux state
#  selinux:
#    state: disabled
#  become: true    

#Si SELinux estuviera activado lo desativamos ya que no lo vamos a utilizar con kubernetes:

- name: Disabling SELinux
  command: "sed -i s/=enforcing/=disabled/g /etc/selinux/config"
  become: true  