# 'nfs-utils','nfs4-acl-tools','wget','python36'
# Paquetes para NFS (network file system)
# Wget es una herramienta libre que permite la descarga de contenidos desde 
# servidores web de una forma simple y rápida. 
- name: instalar paquetes rpm 
  dnf: 
    name: "{{ rpms }}"
    state: present
  become: true  