- name: firewalld setup 1
  command: "firewall-cmd --permanent --add-port=6443/tcp"
  become: true  

- name: firewalld setup 2
  command: "firewall-cmd --permanent --add-port=2379-2380/tcp"
  become: true  

- name: firewalld setup 3
  command: "firewall-cmd --permanent --add-port=10250-10252/tcp"
  become: true  
  
- name: firewalld setup 4
  command: "firewall-cmd --permanent --add-port=10255/tcp"
  become: true  
        
- name: firewalld setup 5
  command: "firewall-cmd --reload"
  become: true  
      
- name: Configuramos kudeadm
  command: "kubeadm config images pull"
  become: true  

- name: Permitiremos el acceso desde los workers 1
  command: "firewall-cmd --permanent --add-rich-rule 'rule family=ipv4 source address=20.23.228.230/32 accept'"
  become: true  

- name: Permitiremos el acceso desde los workers 2
  command: "firewall-cmd --reload"
  become: true      





